# Generated by Django 5.1.6 on 2025-03-05 11:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agency_code', models.CharField(max_length=50, unique=True)),
                ('agency_type', models.CharField(choices=[('police', 'Police Department'), ('dci', 'Directorate of Criminal Investigations (DCI)'), ('nps', 'National Police Service (NPS)'), ('ipoa', 'Independent Policing Oversight Authority (IPOA)'), ('other', 'Other')], max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('jurisdiction_area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('integration_status', models.CharField(choices=[('pending', 'Integration Pending'), ('active', 'Integration Active'), ('suspended', 'Integration Suspended'), ('inactive', 'Integration Inactive')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='AgencyAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('rest', 'REST API'), ('soap', 'SOAP API'), ('ftp', 'FTP Server'), ('sftp', 'SFTP Server'), ('database', 'Direct Database Connection'), ('file', 'File Upload'), ('other', 'Other')], max_length=50)),
                ('connection_url', models.CharField(blank=True, max_length=255)),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('basic', 'Basic Authentication'), ('token', 'Token Authentication'), ('oauth', 'OAuth'), ('certificate', 'Certificate Authentication'), ('other', 'Other')], default='none', max_length=50)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Additional configuration details specific to integration')),
                ('sync_schedule', models.CharField(default='0 0 * * *', help_text='Cron expression for sync schedule', max_length=100)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_config', to='agencies.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Agency Administrator'), ('data_provider', 'Data Provider'), ('analyst', 'Crime Analyst'), ('viewer', 'Data Viewer')], max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='agencies.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_associations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'agency')},
            },
        ),
    ]
