# Generated by Django 5.1.6 on 2025-03-05 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('api', 'REST API'), ('database', 'Database Connection'), ('file', 'File Import'), ('feed', 'Data Feed'), ('scraper', 'Web Scraper'), ('manual', 'Manual Entry')], max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Configuration details for this source')),
                ('is_active', models.BooleanField(default=True)),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text='Mapping between source fields and system fields')),
                ('sync_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('on_demand', 'On Demand')], default='daily', max_length=50)),
                ('cron_expression', models.CharField(blank=True, help_text='Cron expression for custom scheduling', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='agencies.agency')),
            ],
        ),
        migrations.CreateModel(
            name='DataValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('required', 'Required Field'), ('format', 'Format Validation'), ('range', 'Range Check'), ('enum', 'Enumeration Check'), ('unique', 'Uniqueness Check'), ('reference', 'Reference Check'), ('custom', 'Custom Validation')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('configuration', models.JSONField(help_text='Configuration for this validation rule')),
                ('error_action', models.CharField(choices=[('reject', 'Reject Record'), ('warn', 'Log Warning'), ('correct', 'Auto-correct'), ('ignore', 'Ignore')], default='warn', max_length=20)),
                ('priority', models.IntegerField(default=1, help_text='Order in which rules are applied (1 is highest)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='etl.datasource')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ETLJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parameters used for this ETL job')),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_jobs', to='etl.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, null=True)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='etl.etljob')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
