# Generated by Django 5.1.6 on 2025-03-05 11:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crimes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(help_text='Parameters used for this prediction')),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('prediction_start_date', models.DateField()),
                ('prediction_end_date', models.DateField()),
                ('results', models.JSONField(help_text='Prediction results in structured format')),
                ('heatmap_data', models.JSONField(blank=True, help_text='Data for generating prediction heatmaps', null=True)),
                ('confidence_level', models.FloatField(blank=True, help_text='Overall confidence in prediction (0-1)', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_metrics', models.JSONField(blank=True, help_text='Metrics comparing prediction to actual results', null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(help_text='Parameters for the analysis')),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL)),
                ('result_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_for', to='analytics.prediction')),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('hotspot', 'Hotspot Analysis'), ('time_series', 'Time Series Forecasting'), ('regression', 'Regression Model'), ('classification', 'Classification Model'), ('clustering', 'Clustering Model'), ('ensemble', 'Ensemble Model'), ('custom', 'Custom Model')], max_length=20)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ml_models/')),
                ('model_version', models.CharField(default='1.0.0', max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parameters used to train the model')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Performance metrics from validation')),
                ('status', models.CharField(choices=[('in_development', 'In Development'), ('training', 'Training'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='in_development', max_length=20)),
                ('training_date_start', models.DateField(blank=True, null=True)),
                ('training_date_end', models.DateField(blank=True, null=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models', to=settings.AUTH_USER_MODEL)),
                ('target_crime_types', models.ManyToManyField(blank=True, related_name='prediction_models', to='crimes.crimetype')),
            ],
        ),
        migrations.AddField(
            model_name='prediction',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='analytics.predictivemodel'),
        ),
    ]
