# Generated by Django 5.1.6 on 2025-03-05 18:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('crimes', '0002_fix_gin_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crime',
            name='crimes_crim_block_a_653b82_gin',
        ),
        migrations.AddIndex(
            model_name='crime',
            index=django.contrib.postgres.indexes.GinIndex(fields=['block_address'], name='block_address_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
